name: Tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      CONNECTION_TESTS: true

    steps:
      - uses: actions/checkout@v6
        with:
          path: r-client
      - uses: actions/setup-node@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          working-directory: r-client

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: r-client

      - uses: actions/checkout@v6
        with:
          repository: moregeo-it/openeo-test-api
          path: test-api
      - name: setup and run test-api
        working-directory: test-api
        run: | 
          npm install
          npm run adduser r-client r-client
          npm run up

      - name: install openeo package
        working-directory: r-client 
        run: R CMD INSTALL --no-multiarch --with-keep.source .     

      - name: Test R client
        working-directory: r-client/tests
        run: R -f testthat.R